export enum ReportErrorCode {
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_STATUS = 'INVALID_STATUS',
  CHECKOUT_BEFORE_CHECKIN = 'CHECKOUT_BEFORE_CHECKIN',
  UNKNOWN = 'UNKNOWN',
}
